theme: jekyll-theme-minimal
title: The Publications of Severin Aequus
description: Descriptions of, and links to, all available media created by Severin Aequus.<br>[Note: This site only works with Chrome. It does not work with Safari.]
